In [11]:
import numpy as np

# Coefficient matrix for the first set of equations
A1 = np.array([[-1, 1, 2],
               [0, -1, -3],
               [4, -3, 2]])
# Constants matrix for the first set of equations
B1 = np.array([1, -4, 7])

# Calculate the inverse of the coefficient matrix A1
A1_inv = np.linalg.inv(A1)
# Rounding the inverse matrix A1 to two decimal places
A1_inv_rounded = np.around(A1_inv, 2)

# Multiply the inverse of A1 with B1 to find the solution for the first set
solution1 = A1_inv.dot(B1)

# Coefficient matrix for the second set of equations
A2 = np.array([[3, -1, 0],
               [2, -2, 4],
               [5, -6, 2]])
# Constants matrix for the second set of equations
B2 = np.array([4, 8, 13])

# Calculate the inverse of the coefficient matrix A2
A2_inv = np.linalg.inv(A2)
# Rounding the inverse matrix A2 to two decimal places
A2_inv_rounded = np.around(A2_inv, 2)

# Multiply the inverse of A2 with B2 to find the solution for the second set
solution2 = A2_inv.dot(B2)

# Print the solutions and rounded inverse matrices
# For Matrix A1
print(f"Визначник матриці A1: {round(np.linalg.det(A1))}")
print(f"Обернена матриця до матриці A1: \r\n {A1_inv_rounded}")
print(f"Вектор-стовпець рішень: \r\n {solution1}")

# For Matrix A2
print(f"Визначник матриці A2: {round(np.linalg.det(A2))}")
print(f"Обернена матриця до матриці A2: \r\n {A2_inv_rounded}")
print(f"Вектор-стовпець рішень: \r\n {solution2}")



Визначник матриці A1: 7
Обернена матриця до матриці A1: 
 [[-1.57 -1.14 -0.14]
 [-1.71 -1.43 -0.43]
 [ 0.57  0.14  0.14]]
Вектор-стовпець рішень: 
 [2. 1. 1.]
Визначник матриці A2: 44
Обернена матриця до матриці A2: 
 [[ 0.45  0.05 -0.09]
 [ 0.36  0.14 -0.27]
 [-0.05  0.3  -0.09]]
Вектор-стовпець рішень: 
 [ 1. -1.  1.]


In [25]:
import numpy as np
# Matrix for graphical.  Apples trees, Apples and Bananas given:
a = np.array([[3, 0, 0],
              [0, 1, 6],
              [1, 2, 0]])

#Constants matrix given:
b = np.array([60, 23, 30])

x = np.linalg.solve(a, b)

# Calculate the inverse of the coefficient matrix a
a_inv = np.linalg.inv(a)
# Rounding the inverse matrix a to two decimal places
a_inv_rounded = np.around(a_inv, 2)

# Multiply the inverse of a with b to find the solution
solution1 = a_inv.dot(b)

print(f"Визначник матриці a: {round(np.linalg.det(a))}")
print(f"Обернена матриця до матриці a: \r\n {a_inv_rounded}")
print(f"Вектор-стовпець рішень: \r\n {solution1}")
print("Apple trees:", x[0], "Apples:", x[1], "Bananas:", x[2])
res = x[0] + x[1] + 2 * x[2]
print("The Answer is:", (res))


Визначник матриці a: -36
Обернена матриця до матриці a: 
 [[ 0.33  0.    0.  ]
 [-0.17  0.    0.5 ]
 [ 0.03  0.17 -0.08]]
Вектор-стовпець рішень: 
 [20.  5.  3.]
Apple trees: 20.0 Apples: 5.0 Bananas: 3.0
The Answer is: 31.0


In [41]:
import numpy as np

# Define the coefficient matrix for the equations
a = np.array([
    [20, 3, 0],   # Coefficients for the first equation
    [8, 28, 4],   # Coefficients for the second equation
    [4, 12, 32]   # Coefficients for the third equation
])

# Define the constants vector (right-hand side of equations)
b = np.array([800, 900, 600])

# Use np.linalg.solve to find the hourly rates for Designer (D), Developer (R), and Tester (T)
hourly_rates = np.linalg.solve(a, b)
# Rounding the hourly rates to two decimal places
hourly_rates = np.around(hourly_rates, 2)

# Calculate the inverse of the coefficient matrix
inverse_matrix = np.linalg.inv(a)
# Rounding the inverse matrix to two decimal places
inverse_matrix = np.around(inverse_matrix, 3)

# Calculate the determinant of the coefficient matrix
determinant = np.linalg.det(a)
# Rounding the determinant to two decimal places
determinant = np.around(determinant, 2)

# Print the results
print("Визначник матриці a:", determinant)
print("Обернена матриця до матриці a:\n", inverse_matrix)
print("Вектор-стовпець рішень:", hourly_rates)
print("Погодинна оплата дизайнера:", hourly_rates[0],"USD; "  "розробника:", hourly_rates[1],"USD; "  "тестувальника:", hourly_rates[2], "USD")


Визначник матриці a: 16240.0
Обернена матриця до матриці a:
 [[ 0.052 -0.006  0.001]
 [-0.015  0.039 -0.005]
 [-0.001 -0.014  0.033]]
Вектор-стовпець рішень: [36.9  20.69  6.38]
Погодинна оплата дизайнера: 36.9 USD; розробника: 20.69 USD; тестувальника: 6.38 USD
